SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[NonReplicatingTable]'
GO
CREATE TABLE [dbo].[NonReplicatingTable]
(
[Test1] [int] NULL
)
GO

