SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Creating [dbo].[usp_TestSmokeCheck]'
GO
SET QUOTED_IDENTIFIER OFF
GO
CREATE PROCEDURE [dbo].[usp_TestSmokeCheck]
    @Marker NVARCHAR(20) = 'smoke'
AS
BEGIN
    SET NOCOUNT ON;
    SELECT @Marker AS Marker, SYSUTCDATETIME() AS RunAt;
END

GO
SET QUOTED_IDENTIFIER ON
GO

