SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Agents]'
GO
ALTER TABLE [dbo].[Agents] DROP
COLUMN [ReplicatingColumnChange01],
COLUMN [ReplicatingColumnChange02]
GO

