SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Dropping [dbo].[coreINCodeSproc8]'
GO
DROP PROCEDURE [dbo].[coreINCodeSproc8]
GO
PRINT N'Altering [dbo].[Agents]'
GO
ALTER TABLE [dbo].[Agents] DROP
COLUMN [ReplicatingChange8]
GO

