SET NUMERIC_ROUNDABORT OFF
GO
SET ANSI_PADDING, ANSI_WARNINGS, CONCAT_NULL_YIELDS_NULL, ARITHABORT, QUOTED_IDENTIFIER, ANSI_NULLS ON
GO
PRINT N'Altering [dbo].[Regions]'
GO
ALTER TABLE [dbo].[Regions] ADD
[Smoke_ReplNote] [nvarchar] (50) NULL
GO

